language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

notifications:
  email:
    - sam.james.parkinson@gmail.com

before_script:
  - composer install --dev --no-interaction --prefer-source --optimize-autoloader
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter --stdout > build/logs/codeclimate.json
  - cat build/logs/codeclimate.json
  - "curl -X POST -d @build/logs/codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
